name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sachin/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ahufaultapp-cicd" #Must be unique in Heroku
          heroku_email: "sachinkanhurkar78@gmail.com"
          usedocker: true
# code is taken from https://github.com/marketplace/actions/deploy-to-heroku 